force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>MN-{00000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Poster_URL__c.field-meta.xml
<CustomField>
    <fullName>Poster_URL__c</fullName>
    <label>Poster URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDB_movie_Id__c.field-meta.xml
<CustomField>
    <fullName>TMDB_movie_Id__c</fullName>
    <label>TMDB movie Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBSyncDate__c.field-meta.xml
<CustomField>
    <fullName>TMDBSyncDate__c</fullName>
    <label>TMDBSyncDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MovieActions.cls
public with sharing class MovieActions {
    
    //@future(callout=true)
    public static void updateMovieData(List<Id> movieIds) {
        List<Movie__c> movies = MovieActionHelper.getIdsfromMovies(movieIds);
        List<Movie__c> moviesForUpdate = new List<Movie__c>();
        //tmdb tmdbClass = new tmdb();
        for (Movie__c movie : movies) {
            
        TmdbGetMovieDetailsResponse resultData = tmdb.getMovieDetails(movie.TMDB_Movie_Id__c);
        Movie__c updatedMovie = new Movie__c();
        updatedMovie.Id = movie.Id;
        updatedMovie.TMDBSyncDate__c = Date.today();
        updatedMovie.Rating__c = resultData.vote_average;
        updatedMovie.Description__c = resultData.overview;
        updatedMovie.Poster_URL__c = 'https://image.tmdb.org/t/p/original' + resultData.poster_path;
        updatedMovie.Title__c = resultData.original_title;
        updatedMovie.Budget__c = resultData.budget;
        updatedMovie.Revenue__c = resultData.revenue;
        moviesForUpdate.add(updatedMovie);  
        }

        if (moviesForUpdate.size() > 0) {
            update moviesForUpdate;
        }
    }
}