force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>MN-{00000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Poster_URL__c.field-meta.xml
<CustomField>
    <fullName>Poster_URL__c</fullName>
    <label>Poster URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InsertMovieDetails.cls
public with sharing class InsertMovieDetails {
    
    @future(callout=true)
    public static void insertMovieData(String tmdbMovieId) {
        List<Movie__c> movies = new List<Movie__c>();
        //tmdb tmdbClass = new tmdb();
        TmdbGetMovieDetailsResponse resultData = tmdb.getMovieDetails(tmdbMovieId);
        Movie__c movie = new Movie__c();
        movie.Rating__c = resultData.vote_average;
        movie.Description__c = resultData.overview;
        movie.Poster_URL__c = resultData.poster_path;
        movie.Title__c = resultData.original_title;
        movie.Budget__c = resultData.budget;
        movie.Revenue__c = resultData.revenue;
        movies.add(movie);
        
        if (movies.size() > 0) {
            update movies;
        }

    }
}