force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>MN-{00000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDB_movie_Id__c.field-meta.xml
<CustomField>
    <fullName>TMDB_movie_Id__c</fullName>
    <label>TMDB movie Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBSyncDate__c.field-meta.xml
<CustomField>
    <fullName>TMDBSyncDate__c</fullName>
    <label>TMDBSyncDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SyncOutdatedMovieRecs.cls
public with sharing class SyncOutdatedMovieRecs implements Database.Batchable<sObject>, Database.AllowsCallouts {

public Database.QueryLocator start(Database.BatchableContext bc) {
    Date oneMonthAgo = System.today().addMonths(-1);
    return Database.getQueryLocator('SELECT Id, TMDBSyncDate__c, TMDB_Movie_Id__c FROM Movie__c ' +
            'WHERE (TMDBSyncDate__c = NULL OR TMDBSyncDate__c < :oneMonthAgo) ' +
            'AND TMDB_Movie_Id__c != NULL');
}

    public void execute(Database.BatchableContext bc, List<Movie__c> scope) {
        List<Movie__c> moviesToUpdate = new List<Movie__c>();
        
        for (Movie__c movie : scope) {
            TmdbGetMovieDetailsResponse resultData = tmdb.getMovieDetails(movie.TMDB_Movie_Id__c);
                
                movie.TMDBSyncDate__c = Date.today();
                movie.Rating__c = resultData.vote_average;
                movie.Revenue__c = resultData.revenue;
                    
                    moviesToUpdate.add(movie);
                }
                    update moviesToUpdate; 
        }
 
    public void finish(Database.BatchableContext bc) {
        System.debug('Batch finished successfully');
    }
}