force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>MN-{00000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/actual_budget__c.field-meta.xml
<CustomField>
    <fullName>actual_budget__c</fullName>
    <label>Actual budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/LegacyId__c.field-meta.xml
<CustomField>
    <fullName>LegacyId__c</fullName>
    <label>LegacyId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Release_date__c.field-meta.xml
<CustomField>
    <fullName>Release_date__c</fullName>
    <label>Release date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDB_movie_Id__c.field-meta.xml
<CustomField>
    <fullName>TMDB_movie_Id__c</fullName>
    <label>TMDB movie Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <label>Script</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Script__c/fields/LegacyId__c.field-meta.xml
<CustomField>
    <fullName>LegacyId__c</fullName>
    <label>LegacyId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConvertOldFormat.cls
public with sharing class ConvertOldFormat {

    public class MovieData {
        public String id;
        public String name;
        public String tmdb_id;
        public String genre;
        public Decimal rating;
        public Decimal budget;
        public Decimal actual_budget;
        public Decimal revenue;
        public ScriptData script;
        public String release_date;
        public String status;
    }

    public class ScriptData {
        public String id;
        public String name;
        public String description;
    }

    public static Integer ParseJson(String jsonString) {
        List<MovieData> movieList = (List<MovieData>) JSON.deserialize(jsonString, List<MovieData>.class);

        List<Movie__c> moviesToInsert = new List<Movie__c>();
        List<Script__c> scriptsToInsert = new List<Script__c>();

        for (MovieData movieData : movieList) {
            Movie__c movie = new Movie__c();
            movie.LegacyId__c = (String)movieData.id;
            movie.Title__c = movieData.name;
            movie.TMDB_movie_Id__c = (String)movieData.tmdb_id;
            movie.Genre__c = movieData.genre;
            movie.Rating__c = movieData.rating;
            movie.Budget__c = movieData.budget;
            movie.actual_budget__c = movieData.actual_budget;
            movie.Revenue__c = movieData.revenue;
            if (movieData.release_date != null) {
            movie.Release_Date__c = MovieDataImportUtilityHelper.formatDate(movieData.release_date);
            }
            if (movieData.status != null) {
            movie.Status__c = movieData.status;
            }
            moviesToInsert.add(movie);

            if (movieData.script != null) {
                Script__c script = new Script__c();
                script.LegacyId__c = movieData.script.id;
                script.Title__c = movieData.script.name;
                script.Description__c = movieData.script.description;

                scriptsToInsert.add(script);
            }
        }

        if (!scriptsToInsert.isEmpty()) {
            insert scriptsToInsert;
        }

        // Create a map of Script__c records with LegacyId__c as the key
        Map<String, Id> scriptMap = new Map<String, Id>();

        for (Script__c script : [SELECT Id, LegacyId__c FROM Script__c WHERE LegacyId__c != null]) {
            scriptMap.put(script.LegacyId__c, script.Id);
        }

        for (Movie__c movie : moviesToInsert) {
            if (scriptMap.containsKey(movie.LegacyId__c)) {
                movie.Script__c = scriptMap.get(movie.LegacyId__c);
            }
        }

        if (!moviesToInsert.isEmpty()) {
            insert moviesToInsert;
        }

        return moviesToInsert.size();
    }
}